db:
  image: postgres
  environment:
    - POSTGRES_USER=reactions
    - POSTGRES_PASSWORD=reactions
    - POSTGRES_DB=reactions

router:
  build: https://github.com/re-actions/Router.git

apptorize:
  build:

api-spec:
  build: .
  command: behave
  volumes:
    - .:/api-spec
  ports:
    - "8000:8000"
  links:
    - db
